trigger:
  branches:
    include:
      - release-*
      - feature/*
    exclude:
      - main

  paths:
    include:
      - src
    exclude:
      - devops/*

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - main

resources:
  repositories:
    # For type: github, name is <identity>/<repo> as in the examples above. For type: git (Azure Repos), name is <project>/<repo>.
    - repository: coreTemplates
      type: git
      name: Umbrella/Umbrella.Devops
      ref: refs/heads/main
      endpoint: Garaproject

parameters:
  - name: inputSonarScanEnabled
    displayName: "Enable Sonar Scan"
    type: boolean
    default: True
  - name: inputPublishPackage
    displayName: "Publish Package to Nuget.Org"
    type: boolean
    default: False

extends:
  template: dotnet-pakages-pipeline.1.2.yaml@coreTemplates
  parameters:
    MajorVersion: 8
    MinorVersion: 0
    PatchVersion: 0
    Copyright: "FG 2022-2023"
    TargetDotNetFramework: 8.x
    SonarScanEnabled: ${{ parameters.inputSonarScanEnabled }}
    SonarSettings:
      ProjectKey: Umbrella.DDD
      ProjectName: Umbrella.DDD
      TestReportFileName: cobertura.xml
    PublishPackage: ${{ parameters.inputPublishPackage }}
    NugetSecretFileName: Nuget.apikey.txt
    # list of projects to build
    ListOfProjToBuild:
      - path: src/Umbrella.DDD.GCP
        name: Umbrella.DDD.GCP
        publishRequired: false
        isWebProj: False
    # list of packages to push on nuget repo
    ListOfProjToPublish:
      - path: src/Umbrella.DDD
        name: Umbrella.DDD
      - path: src/Umbrella.DDD.GCP
        name: Umbrella.DDD.GCP
